version = 1

test_patterns = ["test/**/test_*.py"]

exclude_patterns = [
    "assets/**",
    "setup/**"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
